config/routes.rb
Rails.application.routes.draw do
  resources :imagehomes
  resources :orders  do 
    collection do
      post :edit_multiple
      put  :update_multiple
      get  :vozvrat
      get  :nedost
    end
  end  
  resources :line_items do
    collection do
      post :remove
    end
  end    
  resources :carts
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'static_pages/home'
  get 'static_pages/sale'
  get 'static_pages/help'
  get 'static_pages/newbook'
  get 'static_pages/static_order'
  resources :searches
  resources :products
  resources :categories
  resources :authors

  root 'imagehomes#index'

end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :cart
 	belongs_to :user
 	has_many   :line_items
  	has_many   :transactions, :class_name => "OrderTransaction"
  
  	validates :first_name, :last_name, :adress, :phone, presence: true
  	validates :phone, length: { minimum: 11,   maximum: 11}

 	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end	



	def count_back_order
	  orders.each do |order|
	  	if order.status = "Возврат"
	  		@order_back = @order_back + 1
	  	end
	  end 	
	end	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def current_user_id
	  return unless session[:user_email]
	  @current_user_id ||= User.find(session[:user_id])
  end
       
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  #before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    
    @line_items = LineItem.all
    @products = Product.all.paginate(:page => params[:page], :per_page => 8)
    @orders = Order.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to product_url, notice: "Ваша корзина пуста"
    return
  end

    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
     @order =  Order.new(order_params)
     @order.add_line_items_from_cart(@cart)
     @order.user_email    = current_user.email
     @order.status    = "Заказ обрабатывается"
    respond_to do |format|
    if @order.save
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
    format.html { redirect_to products_path, notice:'Благодарим за ваш заказ.' }
    format.json { render action: 'show', status: :created,location: @order }
    else
      @cart = current_cart
    format.html { render action: 'new' }
    format.json { render json: @order.errors,status: :unprocessable_entity }
    end
  end
    # @order = current_cart.build_order(order_params)
     
    # @order.cart_id       = current_cart.id
    # @current_cart        = Cart.new(cart_params)
    #  if @order.save
    #   # if @order.purchase
    #      render :action => "success"
    #    
    #  else
    #    render :action => 'new'
    #  end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  #def download_pdf
  #output = ReportPdf.new.to_pdf
#  send_data output, :type => 'application/pdf', :filename => "orders.pdf"
#end

  def edit_multiple
      @orders = Order.find(params[:order_ids]) 
  end
    
  def update_multiple
     if params[:commit] == 'Сохранить'
      @orders = Order.find(params[:order_ids]) 
      @orders.each do |order|
      order.update(order_params)
   end
      flash[:notice] = "Статус заказов обновлен!"
      redirect_to orders_path
     elsif params[:commit] == 'Удалить'
       @orders = Order.find(params[:order_ids]) 
        @orders.each do |order|
          order.destroy
        end
        flash[:notice] = "Заказы удалены!"
        redirect_to orders_path
      end    
  end

  def destroy_multiple
    @orders = Order.find(params[:order_ids]) 
      @orders.each do |order|
        order.destroy
      end
      flash[:notice] = "Заказы удалены!"
      redirect_to orders_path     
  end  


  def vozvrat
    @orders = Order.where(:status => 'Возврат').order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def nedost
    @orders = Order.where(:status => 'Недоставлен').order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:first_name, :last_name, :country, :city, :adress, :phone, :status)
    end

    def cart_params
      params[:cart]
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns ">
  <div class="ramka">
    <%= form_for(@order) do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
     <% end %>

      <div class="field">
        <%= f.label :first_name, "Имя" %><br>
        <%= f.text_field :first_name %>
      </div>

      <div class="field">
        <%= f.label :last_name, "Фамилия" %><br>
        <%= f.text_field :last_name %>
      </div>

      <div class="field">
        <%= f.label :phone, "Номер телефона" %><br>
        <%= f.text_field :phone %>
      </div>

      <div class="field">
        <%= f.label :country, "Страна" %><br>
        <%= f.text_field :country %>
      </div>

      <div class="field">
        <%= f.label :city, "Город" %><br>
        <%= f.text_field :city %>
      </div>

      <div class="field">
        <%= f.label :adress, "Улица и дом" %><br>
        <%= f.text_field :adress %>
      </div>

      

      <div class="actions">
        <%= f.submit "Оформить"%>
      </div>


    <% end %>
</div>
</div>

app/views/orders/edit.html.erb
<h3 class="formi">Изменить статус заказа</h3>

<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns ">
  <div class="ramka">
    <%= form_for (@order) , :html => { :multipart => true} do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
     <% end %>

		<div class="mb1">
		    <%= f.label :status, "Статус заказа" %><br>
		    <p><%= f.select :status, [["Заказ обрабатывается", "Заказ обрабатывается"], ["Отправлен", "Отправлен"], ["Возврат", "Возврат"], ["Недоставлен", "Недоставлен"]], {}, id: "simple-example"   %></p>
		</div>

		<div class="actions">
		    <%= f.submit "Оформить"%>
		</div>

	<% end %>
</div>
<br>
		
<%= link_to 'Посмотреть', @order %> |
<%= link_to 'Назад', orders_path %>

<script>
      $(document).ready(function() {
    $('select#simple-example').select2();
    });
</script>

app/views/orders/edit_multiple.html.erb
<h3 class="formi">Изменить статус заказов</h3>

<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns ">
  <div class="ramka">
  <%= form_for :order, :url => update_multiple_orders_path, :html => { :method => :put } do |f| %>

     <ul>
      <% for order in @orders %>
      <li>
        <%= h order.user_email %>
        <%= hidden_field_tag "order_ids[]", order.id%>
      </li>
      <% end %>
    </ul>

		<div class="mb1">
		    <%= f.label :status, "Статус заказа" %><br>
		    <p><%= f.select :status, [["Заказ обрабатывается", "Заказ обрабатывается"], ["Отправлен", "Отправлен"], ["Возврат", "Возврат"], ["Недоставлен", "Недоставлен"]], {}, id: "simple-example"   %></p>
		</div>

		<div class="actions">
		    <%= f.submit 'Сохранить'%>
        <%= f.submit 'Удалить',  data: { confirm: 'Вы уверены?' }%>
		</div>

	<% end %>
</div>
<br>
		
<%= link_to 'Посмотреть', @order %> |
<%= link_to 'Назад', orders_path %>

<script>
      $(document).ready(function() {
    $('select#simple-example').select2();
    });
</script>

app/views/orders/index.html.erb
<%if signed_in?%>
  <% if not  current_user.admin? %>
    <p id="notice"><%= notice %></p>

    <h3 class="booking">Ваши заказы</h3>
    <div class="pages">
    <%= will_paginate @orders, :class => 'apple_pagination' %>
 </div>
   <table class="features-table">
     <thead>
       <tr>
           <th>От кого</th>
           <th>Почта</th>
           <th>Телефон</th>
           <th>Адрес</th>
           <th>Дата</th>
           <th>Статус</th>
           <th></th>
       </tr>
     </thead>
      <% Order.where(user_email: current_user.email).order("created_at DESC").each do |orderi| %>
            <tbody>
                  <tr>
                    <td><%= orderi.first_name %> <%= orderi.last_name %></td>
                    <td><%= orderi.user_email %></td>
                    <td><%= orderi.phone %></td>
                    <td><%= orderi.country %>, <%= orderi.city %>, <%= orderi.adress %></td>
                    <td><%= orderi.created_at %></td>
                    <td><%= orderi.status %></td>
                    <td><%= link_to "Посмотреть", orderi %></td>
                  </tr>
              <% end %>
     </tbody>
    </table>
  <% else %>
    <table class="features-table">
     <thead>
       <tr>
           <th>Заказы</th>
           <th>Возврат</th>
           <th>Недоставленные</th>
           <th>Заказ на обработке</th>
       </tr>
     </thead>
            <tbody>
                  <tr>
                    <td><%= @orders.count %></td>
                    <td><%= @orders.where(:status => 'Возврат').count %></td>
                    <td><%= @orders.where(:status => 'Недоставлен').count %></td>
                    <td><%= @orders.where(:status => 'Заказ обрабатывается').count %></td>
                  </tr>
     </tbody>
    </table>
    <h3 class="booking">Заказы</h3>
      <div class="pages">
        <%= will_paginate @authors, :class => 'apple_pagination' %>
      </div>

<%= form_tag edit_multiple_orders_path do %>

     <table class="features-table">
       <thead>
         <tr>
           <th></th>
           <th>От кого</th>
           <th>Почта</th>
           <th>Телефон</th>
           <th>Адрес</th>
           <th>Дата</th>
           <th>Статус</th>
           <th></th>
         </tr>
       </thead>
           <% @orders.order("created_at DESC").each do |orderi| %>
                <tbody>
                  <tr>
                    <td><%= check_box_tag "order_ids[]", orderi.id %></td>
                    <td><%= orderi.first_name %> <%= orderi.last_name %></td>
                    <td><%= orderi.user_email %></td>
                    <td><%= orderi.phone %></td>
                    <td><%= orderi.country %>, <%= orderi.city %>, <%= orderi.adress %></td>
                    <td><%= orderi.created_at %></td>
                    <td><%= orderi.status %></td>
                    <td><%= link_to "Посмотреть", orderi %></td>
                  </tr>
              <% end %>
       </tbody>
      </table>
      <%= submit_tag "Изменить/Удалить" %>
      <% end %>


     <div class="pages">
        <%= will_paginate @orders, :class => 'apple_pagination' %>
    </div>

    <%= link_to 'Назад', products_path %> |
    <%= link_to 'Статистика продаж', static_pages_static_order_path %> |
    <%= link_to 'Возврат', vozvrat_orders_path %> |
    <%= link_to 'Недоставленные', nedost_orders_path %> 

  <% end %>
  <% end %>
    

app/views/orders/nedost.html.erb
 <%if signed_in?%>
  <% if  current_user.admin? %>
      <h3 class="booking">Недоставленные</h3>

       <table class="features-table">
         <thead>
           <tr>
             <th>От кого</th>
             <th>Почта</th>
             <th>Телефон</th>
             <th>Адрес</th>
             <th>Дата</th>
             <th>Статус</th>
             <th></th>
           </tr>
         </thead>
             <% @orders.each do |orderi| %>
                  <tbody>
                    <tr>
                      <td><%= orderi.first_name %> <%= orderi.last_name %></td>
                      <td><%= orderi.user_email %></td>
                      <td><%= orderi.phone %></td>
                      <td><%= orderi.adress %></td>
                      <td><%= orderi.created_at %></td>
                      <td><%= orderi.status %></td>
                      <td><%= link_to "Посмотреть", orderi %></td>
                    </tr>
                <% end %>
         </tbody>
        </table>

     <div class="pages">
        <%= will_paginate @orders, :class => 'apple_pagination' %>
    </div>

  <% end %>
  <% end %>

app/views/orders/new.html.erb
<h3 class="formi">Заказ</h3>

	<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/orders/railure.html.erb
FAILURE

app/views/orders/show.html.erb
<%if signed_in?%>
    <h3 class="booking">Заказ</h3>
    <p class="booking">(<%= @order.status %>)</p>
    <table class="features-table">
         <thead>
           <tr>
             <th>Название</th>
             <th>Количество</th>
             <th>Дата</th>
             <th>Адрес</th>
           </tr>
         </thead>

          <% LineItem.where(order_id: @order.id).each do |line_item| %>
            <% Product.where(id: line_item.product_id).each do |product| %>
              <tbody>
                <tr>
                  <td class="grey"><%= link_to product.title, product %></td>
                  <td><%= line_item.quantity %></td>
                  <td><%= @order.created_at %></td>
                  <td><%= @order.country %>, <%= @order.city %>, <%= @order.adress %></td>
                  <% if current_user.admin? %>
                    <td><%= link_to "Изменить статус заказа", edit_order_path(@order) %></td>
                  <% end %>  
                </tr>
            <% end %>
          <% end %>
            </tbody>
    </table>

    <%= link_to 'Назад', orders_path %>
<% end %>

app/views/orders/success.html.erb
SUCCESS!

app/views/orders/vozvrat.html.erb
<%if signed_in?%>
  <% if current_user.admin? %>
    <h3 class="booking">Возврат</h3>

         <table class="features-table">
           <thead>
             <tr>
               <th>От кого</th>
               <th>Почта</th>
               <th>Телефон</th>
               <th>Адрес</th>
               <th>Дата</th>
               <th>Статус</th>
               <th></th>
             </tr>
           </thead>
               <% @orders.each do |orderi| %>
                    <tbody>
                      <tr>
                        <td><%= orderi.first_name %> <%= orderi.last_name %></td>
                        <td><%= orderi.user_email %></td>
                        <td><%= orderi.phone %></td>
                        <td><%= orderi.adress %></td>
                        <td><%= orderi.created_at %></td>
                        <td><%= orderi.status %></td>
                        <td><%= link_to "Посмотреть", orderi %></td>
                      </tr>
                  <% end %>
           </tbody>
          </table>

    <div class="pages">
        <%= will_paginate @orders, :class => 'apple_pagination' %>
    </div>

  <% end %>
<% end %>          