config/routes.rb
Rails.application.routes.draw do
  resources :imagehomes
  resources :orders  do 
    collection do
      post :edit_multiple
      put  :update_multiple
      get  :vozvrat
      get  :nedost
    end
  end  
  resources :line_items do
    collection do
      post :remove
    end
  end    
  resources :carts
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'static_pages/home'
  get 'static_pages/sale'
  get 'static_pages/help'
  get 'static_pages/newbook'
  get 'static_pages/static_order'
  resources :searches
  resources :products
  resources :categories
  resources :authors

  root 'imagehomes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.paginate(:page => params[:page], :per_page => 8)
    @products = Product.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
     @products = Product.all.paginate(:page => params[:page], :per_page => 8)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Жанр добавлен.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Жанр обновлен.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Жанр удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns ">
  <div class="ramka">
    <%= form_for(@category) do |f| %>
      <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title, "Название" %><br>
        <%= f.text_field :title %>
      </div>
      <div class="actions">
        <%= f.submit "Сохранить"%>
      </div>
    <% end %>
  </div>
</div>  

app/views/categories/edit.html.erb
<h4 class="formi">Редактировать</h4>

<%= render 'form' %>

<%= link_to 'Назад', categories_path %>

app/views/categories/index.html.erb
<%if signed_in?%>
  <% if  current_user.admin? %>
    <h4 class="booking">Жанры</h4>
      <table class="features-table">
        <thead>
        <tr>
          <th>Название</th>
          <th><%= link_to 'Добавить', new_category_path, :class => "add"  %></th>
        </tr>
        </thead>

        <tbody>
        <% @categories.each do |category| %>
            <tr>
              <td class="grey"><%= link_to category.title, category %></td>
              <td><%= link_to 'Редактировать', edit_category_path(category) %></td>
              <td><%= link_to 'Удалить', category, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
          <table class="features-table">
            <thead>
                <tr>
                  <th><h4 class="booking">Жанры</h4></th>
                </tr>
                </thead>

                <tbody>
                <% @categories.each do |category| %>
                    <tr>
                      <td><%= link_to category.title, category %></td>
                    </tr>
                <% end %>
            </tbody>
          </table>


    <% end %>
  <% else %>
  <table class="features-table">
            <thead>
                <tr>
                  <th><h4 class="booking">Жанры</h4></th>
                </tr>
                </thead>

                <tbody>
                <% @categories.each do |category| %>
                    <tr>
                      <td><%= link_to category.title, category %></td>
                    </tr>
                <% end %>
            </tbody>
          </table>
<% end %>  

<div class="pages">
  <%= will_paginate @categories, :class => 'apple_pagination' %>
</div>

app/views/categories/new.html.erb
<h4 class="formi">Добавить</h4>

  <%= render 'form' %>

<%= link_to 'Назад', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class="booking"><%=  @category.title %></h3>

<div class="column">
  <ul class="movies-grid no-bullet row">
    <% Product.where(category_id: @category.id).each do |product| %>
        <li class="large-3 medium-4 small-12 column pages">
          <div class="movie-card padly">
            <%= link_to product, class: "poster" do %>
              <%= image_tag product.photo.url %>
                <% end %>
                  <div class="movie-info ell glassy-bg padmy padlx">
                    <div class="title">
                      <h6><%= product.title %></h6>
                    </div>
                  <p class="left price label movie-label radius"> <%= product.price %> руб.</p>
                   </div>
          </div>
        </li>
    <% end %>
  </ul>
</div>

<div class="pages">
  <%= will_paginate @products, :class => 'apple_pagination' %>
</div>


<%= link_to 'Назад', products_path %>