config/routes.rb
Rails.application.routes.draw do
  resources :imagehomes
  resources :orders  do 
    collection do
      post :edit_multiple
      put  :update_multiple
      get  :vozvrat
      get  :nedost
    end
  end  
  resources :line_items do
    collection do
      post :remove
    end
  end    
  resources :carts
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'static_pages/home'
  get 'static_pages/sale'
  get 'static_pages/help'
  get 'static_pages/newbook'
  get 'static_pages/static_order'
  resources :searches
  resources :products
  resources :categories
  resources :authors

  root 'imagehomes#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :author
  belongs_to :category

 

  before_destroy :ensure_not_referenced_by_any_line_item
  
  has_many :line_items
  has_many :payments, class_name: :PaypalInstantPaymentNotification


  has_attached_file :photo
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
def paid?
  payments.find_by(status: 'Completed').present?
end

def self.search(search)
	if search
		Product.where(["title LIKE ?","%#{search}%"])
	else
		all
	end
end	


 private


 # убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper_method :sort_column, :sort_direction
  respond_to :html, :json
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
   @products = Product.search(params[:search]).order(sort_column + " " + sort_direction).order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product    = Product.new
    @authors    = Author.all
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @authors    = Author.all
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end  

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
      if stale?(@latest_order)
        respond_to do |format|
          format.atom
        end
      end
  end    

 def search
    @search = Product.search do
      fulltext params[:search]
      facet(:why_author)
      paginate :page => params[:page] || 1, :per_page => 8
   end
     @products = @search.results
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :author_id, :category_id, :isbn, :year, :description, :filming, :quantity, :price, :sale, :photo, :new, :publishing, :old_price, :cover)
    end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "title"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns ">
  <div class="ramka">
    <%= form_for @product, :html => { :multipart => true} do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb1">
        <%= f.label :Название %><br>
        <%= f.text_field :title %>
      </div>

        <div class="mb1">
          <%= f.label "Автор" %> <br />
          <p><%= collection_select(:product,:author_id,@authors,:id,:full_name, {}, id: "simple-example") %></p>
        </div>

      <div class="mb1">
        <%= f.label "Категория" %> <br />
        <p><%= collection_select(:product,:category_id,@categories,:id,:title, {}, id: "simple-example")%></p>
     
      </div>

      <div class="mb1">
        <%= f.label "Издательство" %> <br />
        <%= f.text_field :publishing %>
      </div>

      <div class="mb1">
        <%= f.label :isbn %><br>
        <%= f.text_field :isbn %>
      </div>

      <div class="mb1">
        <%= f.label :cover, "Обложка" %><br>
        <p><%= f.select :cover, [["Мягкая", "Мягкая"], ["Твердая", "Твердая"]], {}, id: "simple-example"  %></p>
      </div>

      <div class="mb1">
        <%= f.label :Описание %><br>
        <%= f.text_area :description, rows: 6 %>
      </div>

      <div class="mb1">
        <%= f.label :Экранизации %><br>
        <%= f.text_field :filming %>
      </div>

      <div class="mb1">
        <%= f.label :Количество_на_складе %><br>
        <%= f.number_field :quantity %>
      </div>

      <div class="mb1">
        <%= f.label :Распродажа %><br>
        <p><%= f.select :sale, [["Нет", "false"], ["Да", "true"]], {}, id: "simple-example"  %></p>
      </div>

      <div class="mb1">
        <%= f.label :new ,"Новинка" %><br>
        <p><%= f.select :new, ([["Нет", "false"], ["Да", "true"]]), {}, id: "simple-example" %></p>
      </div>

      <div cclas="mb1">
        <%= f.label :Цена %><br>
        <%= f.text_field :price %>
       </div>

       <div cclas="mb1">
        <%= f.label :old_price, "Старая цена" %><br>
        <%= f.text_field :old_price %>
       </div>

      <div class="mb1">
        <%= f.label        :Изображение %>
        <%= f.file_field :photo %>
        <% if not @product.photo.nil? %>
          <%= image_tag @product.photo, class: "img-edit" %>
        <% end %>  
      </div>


      <div class="actions">
        <%= f.submit "Сохранить", class: "succe"%>
      </div>
    <% end %>
  </div>
</div>  
<script>
      $(document).ready(function() {
    $('select#simple-example').select2();
    });
</script>

    

app/views/products/_productind.html.erb
<h4 class="column formi">Каталог</h4>
        <div class="column">
          <ul class="movies-grid no-bullet row">
          
              <% @products.each do |product| %>
                  
              
                  <li class="large-3 medium-4 small-12 column pages">
                    <div class="movie-card padly">
                    <% if product.new? %>
                     <div class="ribbon-wrapper-green"><div class="ribbon-green">Новинка</div></div>
                     <% end %>
                     <% if product.sale? %>
                        <div class="ribbon-wrapper-red"><div class="ribbon-red">Скидки</div></div>
                     <% end %>
                      <%= link_to product, class: "poster" do %>
                          <%= image_tag product.photo.url, class: "poster" %>
                      <% end %>
                      <div class="movie-info ell glassy-bg padmy padlx">
                        <div class="title">
                          <h6><%= product.title %></h6>
                        </div>
                         <div class="label movie-label radius mb1">Цена: <%= product.price %>руб.</div>
                         <% if product.sale? %>
                        <div class="label1 movie-label radius mb1">Цена до: <%= product.old_price %>руб.</div>
                        <% end %>
                      </div>
                    </div>
                  </li>
              <% end %>
          </ul>
        </div>

app/views/products/_products.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

app/views/products/edit.html.erb
<h3 class="formi">Редактировать информацию о книге</h3>

<%= render 'form' %>

<%= link_to 'Показать', @product %> |
<%= link_to 'Назад', products_path %>

app/views/products/index.html.erb
<%if signed_in?%>
  <% if  current_user.admin? %>
     <h4 class="column formi">Каталог</h4>
        <table class="features-table pretty">
          <thead>
          <tr>
            <th class="pretty"><%= sortable "title", "Название" %></th>
            <th >Автор</th>
            <th>Категория</th>
            <th class="pretty"><%= sortable "quantity",  "Количество"%></th>
            <th class="pretty"><%= sortable "price", "Цена" %></th>
            <th class="pretty"><%= sortable "created_at", "Дата"  %></th>
            <th class="pretty"><%= link_to 'Добавить', new_product_path, :class => "add" %></th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>

          <% @products.each do |product| %>
              <tr>
                <td class="grey"><%= link_to product.title, product %></td>
                <td class="grey"><%= link_to  Author.find(product.author_id).full_name,  Author.find(product.author_id)  %></td>
                <td class="grey"><%= link_to  Category.find(product.category_id).title, Category.find(product.category_id)  %></td>
                <td class="grey"><%= product.quantity %></td>
                <td class="grey"><%= product.price %> руб.</td>
                <td class="grey"><%= product.created_at %></td>
                <td><%= link_to 'Показать', product %></td>
                <td><%= link_to 'Редактировать', edit_product_path(product) %></td>
                <td><%= link_to 'Удалить', product, method: :delete %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
   <% else %>  
      <%= render "productind" %>
  <% end %>
  </br>
    
  <% else %>
      <%= render "productind" %>
    </br>
<% end %>

<div class="pages">
  <%= will_paginate @products, :class => 'apple_pagination' %>
</div>


  

app/views/products/new.html.erb
<h3 class="formi">Новая книга</h3>

<%= render 'form' %>

<%= link_to 'Назад', products_path %>

app/views/products/show.html.erb
<div class="pages">
  <div class="large-3 medium-4 small-12 column pages ">
  <% if @product.new? %>
    <div class="ribbon-wrapper-green"><div class="ribbon-green">Новинка</div></div>
  <% end %>
  <% if @product.sale? %>
    <div class="ribbon-wrapper-red"><div class="ribbon-red">Скидки</div></div>
  <% end %>
    <%=image_tag @product.photo.url %>
  </div>

  <div class="large-9 small-12 column">
    <h4> <%= @product.title %>
        (<%= link_to Author.find(@product.author_id).full_name, author_path(@product.author_id) %>)
    </h4>
    <div>Категория: <%= link_to Category.find(@product.category_id).title, category_path(@product.category_id)%></div>
    <div>ISBN: <%= @product.isbn %></div>
    <div>Издательство: <%= @product.publishing %></div>
    <div>Обложка: <%= @product.cover %></div>
    </br>
    <% if @product.sale? %>
      <div class="label movie-label radius mb1"> Цена: <%= @product.price %>руб.</div>
      <div class="label1 movie-label radius mb1">Старая цена: <%= @product.old_price %>руб.</div>
    <% else %>  
      <div class="label movie-label radius mb1"> Цена: <%= @product.price %>руб.</div>
    <% end %>  
    <%if signed_in?%>
      <% if not current_user.admin? %> 
         <% if @product.quantity > 0 %>  
        <div >  <%= button_to "Добавить в корзину", line_items_path(product_id: @product.id) , class: "mebtn" %></div>
        <% else %>
        <p>Товара нет в наличии</p>
        <% end %>
      <% end %>
    <% end %>    
    <div class="bordera"><h5> Описание </h5></div>
    <p class="texti"><%= @product.description %></p>  
    <div class="bordera"><h5> Экранизации </h5></div>

    <div class="filming">
       <%= @product.filming %>
    </div>

   </br>
  </div>


<%if signed_in?%>
  <% if  current_user.admin? %>
    <%= link_to 'Редактировать', edit_product_path(@product) %> |
    <%= link_to 'Удалить', product_path(@product), method: :delete, data: { confirm: 'Вы уверены?' } %> |
  <% end %>
<% end %>    

  <%= link_to 'Назад', products_path %>
</div>