config/routes.rb
Rails.application.routes.draw do
  resources :imagehomes
  resources :orders  do 
    collection do
      post :edit_multiple
      put  :update_multiple
      get  :vozvrat
      get  :nedost
    end
  end  
  resources :line_items do
    collection do
      post :remove
    end
  end    
  resources :carts
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  get 'static_pages/home'
  get 'static_pages/sale'
  get 'static_pages/help'
  get 'static_pages/newbook'
  get 'static_pages/static_order'
  resources :searches
  resources :products
  resources :categories
  resources :authors

  root 'imagehomes#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	  has_many :products, dependent: :destroy	
	  has_attached_file :photo
  	  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_one  :order 

	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id)
			if current_item
				current_item.quantity += 1	
			else
				current_item = line_items.build(product_id: product_id)
			end
				current_item
	end

	def remove_product(product_id)
		current_item = line_items.find_by(product_id: product_id)
			if current_item
				current_item.quantity -= 1	
			else
				current_item = line_items.build(product_id: product_id)
			end
				current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
end

app/models/imagehome.rb
class Imagehome < ActiveRecord::Base
	has_attached_file :slider
    validates_attachment_content_type :slider, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart


  def total_price
	product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base

	belongs_to :cart
 	belongs_to :user
 	has_many   :line_items
  	has_many   :transactions, :class_name => "OrderTransaction"
  
  	validates :first_name, :last_name, :adress, :phone, presence: true
  	validates :phone, length: { minimum: 11,   maximum: 11}

 	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end	



	def count_back_order
	  orders.each do |order|
	  	if order.status = "Возврат"
	  		@order_back = @order_back + 1
	  	end
	  end 	
	end	

end

app/models/order_transaction.rb
class OrderTransaction < ActiveRecord::Base
	belongs_to :order
  serialize :params
  
  def response=(response)
    self.success       = response.success?
    self.authorization = response.authorization
    self.message       = response.message
    self.params        = response.params
  rescue ActiveMerchant::ActiveMerchantError => e
    self.success       = false
    self.authorization = nil
    self.message       = e.message
    self.params        = {}
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :author
  belongs_to :category

 

  before_destroy :ensure_not_referenced_by_any_line_item
  
  has_many :line_items
  has_many :payments, class_name: :PaypalInstantPaymentNotification


  has_attached_file :photo
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
def paid?
  payments.find_by(status: 'Completed').present?
end

def self.search(search)
	if search
		Product.where(["title LIKE ?","%#{search}%"])
	else
		all
	end
end	


 private


 # убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'существуют товарные позиции')
			return false
		end
	end
end

app/models/search.rb
class Search < ActiveRecord::Base 


	def search_products
		
		products = Product.all

		products = products.where("title like ?", "%#{keywords}%") 		if keywords.present?
		products = products.where("category_id LIKE ?",category_id)		if category_id.present?
		products = products.where("author_id LIKE ?",author_id) 		if author_id.present?
		products = products.where("price >= ?", min_price) 				if min_price.present?
		products = products.where("price <= ?",max_price)				if max_price.present?
		products = products.where("isbn LIKE ?",isbn) 					if isbn.present?

		return products
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def current_user_id
	  return unless session[:user_email]
	  @current_user_id ||= User.find(session[:user_id])
  end
       
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  	end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/imagehomes_helper.rb
module ImagehomesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_header.html.erb
<div class="row">
  <nav class="top-bar column" data-topbar>
 
      <ul class="title-area">
        <li class="name">
          <h1>
            <div class="logo">
              <%= link_to products_path, class: "poster" do %>
               <%= image_tag 'logo.png', class: "logi" %>
          <% end %>
        </div>
          </h1>
        </li>
        <li class="searchi">
          <%= form_tag products_path, :method => 'get' do %>
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>
          <%= text_field_tag :search, params[:search] %>
          <% end %>
        </li>

        <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>

      </ul>

      <section class="top-bar-section">
        <ul class="right">
            <%if signed_in?%>
              <li>
               <%if signed_in?%>
                  <% if not current_user.admin? %>
                    <% if !session[:cart_id].nil? %>
                      <%= link_to "Корзина", Cart.find(session[:cart_id]) %>
                        <% else %>
                      <%= link_to "Корзина", Cart.new %>
                    <% end %> 
                <% end %>
                <li><%= link_to "Заказы", orders_path %></li>  
              <% end %>    
              </li>
              <li><%=link_to current_user.email, edit_user_registration_path%></li>
              <li><%=link_to "Выйти", destroy_user_session_path, method: :delete%></li>
            <%else%>
              <li><%=link_to "Регистрация", new_user_registration_path%></li>
              <li><%=link_to "Войти", new_user_session_path%></li>
            <%end%>
          </ul>  
      </section>

    </nav>
    </br>
    <nav class="top-bar column" data-topbar>
 
      <ul class="title-area">
        <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
      </ul>
           

      <section class="top-bar-section bari">
        <ul class="left">
              <li><%= link_to "ГЛАВНАЯ",         imagehomes_path %></li> 
              <li><%= link_to "КАТАЛОГ КНИГ",    products_path %></li> 
              <li><%= link_to "АВТОРЫ",          authors_path %></li> 
              <li><%= link_to "ЖАНРЫ",           categories_path %></li> 
              <li><%= link_to "СКИДКИ",          static_pages_sale_path %></li>
              <li><%= link_to "НОВИНКИ",         static_pages_newbook_path %></li>
              <li><%= link_to "ПОИСК",           new_search_path %></li> 
              <li><%= link_to "ПОМОЩЬ",          static_pages_help_path %></li>
          </ul>  
      </section>

    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>

   	 <%= render "layouts/header" %>
         
     <%= render "layouts/alerts" %>
     
         
    
   <div id="main-content" class="row full-min-height">
    <%= yield %>
  </div>
         

     
         
     
          <footer class="row">
            <div class="large-12 columns"><hr/>
              <div class="row">
     
                <div class="large-6 columns">
                  <p>Контактный номер: 8-800-444-8-444</p>
                  <p>© Читай-ка</p>
                </div>
     
                <div class="large-6 columns">
                  <ul class="inline-list right">
                    <li><%= link_to "Книги",  products_path   %></li>
                    <li><%= link_to "Авторы", authors_path    %></li>
                    <li><%= link_to "Жанры",  categories_path %></li>
                  </ul>
                </div>
     
              </div>
            </div>
          </footer>
     
         
     
        </div>
      </div>
    


  </body>
</html>